platform :ios, '9.0'

target 'XMLYFM' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for XMLYFM
    pod 'XMLYBase'
    pod 'XMLYMain'

end
